### PR TITLE
fix(check-tag-names): Workaround for 'constructor' key in tagNamePreference

### LINKED ISSUE #537: Can't set preference for 'constructor' in tagNamePreference due to upstream issue
In the Wikimedia config, we want to allow `@class` and `@constructor`.

This should be possible with the following config:
```json
{
  "tagNamePreference": {
    "class": "class",
    "constructor": "constructor"
  }
}
```

However due to an upstream issue (https://github.com/eslint/eslint/issues/13289) it is impossible to use settings keys that exist on Object.prototype (so `constructor`, `toString` etc.).

### PR DESCRIPTION
**Pull request by edg2s**
Fixes #537

### CODE REVIEW

File: src/jsdocUtils.js [hunk 1]
```diff
@@ -216,20 +216,27 @@ const getPreferredTagName = (
...
+  });
+
+  if (tagPreferenceFixed.includes(name)) {
+    return tagPreferenceFixed[name];
   }
 
   const tagNames = getTagNamesForMode(mode, context);
 
-  const preferredTagName = _.findKey(tagNames, (aliases) => {
+  const preferredTagName = Object.keys(tagNames).find((aliases) => {
```
Comment (brettz9) [inline src/jsdocUtils.js:239]: Sorry, made some premature changes re: further reducing lodash, but working on fixing locally.

**Comment by brettz9** [comment]
Thanks for the issue and PR!
