### PR TITLE
fix(`lines-before-block`): Only trigger after ';', '}', '|', and '&'

### LINKED ISSUE #1379: lines-before-block should not trigger for the first item inside functions and constructors
## ESLint Config

```json
{
    "jsdoc/lines-before-block": "error"
}
```

## ESLint sample

```js
declare class SomeClass {
  // Not ok:
  constructor(
    /** Some doc */
    param: number,
  );

  // Not ok:
  method(
    /** Some doc */
    param: number,
  ): void;

  // Ok:
  /** Some doc */
  prop: number;
}

// Not ok:
type SomeFunctionAlias =
   /**
     * @param param - Some doc.
     */
    (param: number) => void;

// Not ok:
type SomeFunctionAlias2 = (
   /**
     * @param param - Some doc.
     */
    param: number
) => void;
```

## Environment

- Node version: v20.15.0
- ESLint version v9.26.0
- `eslint-plugin-jsdoc` version: ^50.6.11

## Expected behavior
I expected there to be a configuration option to be able to avoid having to add newlines before all of the places linted in that snippet.

## Actual behavior
The rule requires adding a newline but this causes conflicts with Prettier. Subjectively I also think it looks ugly.

### PR DESCRIPTION
**Pull request by LukeAbby**
Fixes #1379 and #1343.

I initially went for a targeted fix that would only solve my issue, #1379, but I noticed that all punctuators didn't seem to me like reasonable places to insert a line before. As I had also been facing #1343 solving it was nice too.

Of course what "feels" right is obviously subjective so let me know if you want me to put this behind an option. I considered exposing `lintedPunctuators` as an option but it felt too granular. Disabling `&` could be useful to users of Prettier that want to set `ignoreSameLine` to `false` though. Specifically, Prettier really isn't fond of the formatting in this snippet:

```js
type IntersectionDocumentation =
    & { someProp: number }
    /** Description. */
    & { otherProp: string };
```

And will format it like so:
```js
type IntersectionDocumentation = { someProp: number } /** Description. */ & { otherProp: string };
```
Which I think looks terrible.

As a final note, currently the option `checkBlockStarts` is set to actually control linting after _all_ punctuators because I noticed a number of tests expected it to work that way for more than just `{`, like the array test etc. This makes it a bit of a misnomer but it appears it was already a bit of a misnomer.

### CODE REVIEW

File: src/rules/linesBeforeBlock.js [hunk 1]
```diff
@@ -1,5 +1,12 @@
 import iterateJsdoc from '../iterateJsdoc.js';
 
+/**
+ * `;` ends a previous statement, `}` ends a previous block, `|` is seen the middle of a union, and
+ * `&` is seen in the middle of an intersection. All other punctuators are for things like arrays,
+ * functions, type aliases, and so on that shouldn't require a line before it.
+ */
+const lintedPunctuators = [';', '}', '|', '&'];
```
Comment (brettz9) [inline src/rules/linesBeforeBlock.js:8]:
```suggestion
const lintedPunctuators = new Set([';', '}', '|', '&']);
```

File: src/rules/linesBeforeBlock.js [hunk 2]
```diff
@@ -19,8 +26,14 @@ export default iterateJsdoc(({
...
 
   const tokensBefore = sourceCode.getTokensBefore(jsdocNode, {includeComments: true});
-  const tokenBefore = tokensBefore.slice(-1)[0];
-  if (!tokenBefore || (tokenBefore.value === '{' && !checkBlockStarts)) {
+  const tokenBefore = tokensBefore.at(-1);
+  if (
+    !tokenBefore || (
+      tokenBefore.type === 'Punctuator' &&
+      !checkBlockStarts &&
+      !lintedPunctuators.includes(tokenBefore.value)
```
Comment (brettz9) [inline src/rules/linesBeforeBlock.js:34]:
```suggestion
      !lintedPunctuators.has(tokenBefore.value)
```

**Review by brettz9 — CHANGES_REQUESTED** [review]
This LGTM. Just the suggested tweak on using a `Set`.

**Comment by LukeAbby** [comment]
Thanks for the review! Bad habit of mine to not use a `Set`. Probably comes from knowing that `Set#has` is slower than `Array#includes` for small array but it leads to clearer code and that's what's most important.

**Review by brettz9 — APPROVED** [review]
